services:
  - type: web
    name: tb-cough-inference
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install poetry==2.1.3
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: POETRY_VERSION
        value: 2.1.3
      - key: PIP_NO_CACHE_DIR
        value: "1" 