services:
  - type: web
    name: tb-cough-inference
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind=0.0.0.0:$PORT --timeout 120 --workers 1 --max-requests 1000 --max-requests-jitter 50 --preload app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 